# Site settings
title: Air Quality | sensors.AFRICA meets HealthTools
email: airquality@codeforafrica.org
description.de: > # this means to ignore newlines until "description.en:"
  Wir entwickeln Feinstaubmessger채te und verteilen sie 체ber die
  Stadt Stuttgart.
description.en: > # this means to ignore newlines until "baseurl:"
  Wir entwickeln Feinstaubmessger채te und verteilen sie 체ber die
  Stadt Stuttgart.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://airquality.codeforafrica.org"
enforce_url: "airquality.codeforafrica.org"

twitter_username: Code4Africa
github_username: CodeForAfrica
medium_publication: code-for-africa

# Build settings
markdown: kramdown
